steps:
  # gr: need to add auth here!
  # gr: name isn't a nice name, it's a specific command :)
- name: node
  entrypoint: npm
  args: ['install']
  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/gweb-kandinsky/github.com/newchromantics/popdynamicsharetest:$SHORT_SHA', '.' ]
